parameters:
#    my_site_data_base.example.class: MySite\DataBaseBundle\Example

services:
#    my_site_data_base.example:
#        class: %my_site_data_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
