parameters:
#    my_site_c_dominguez.example.class: MySite\CDominguezBundle\Example

services:
#    my_site_c_dominguez.example:
#        class: %my_site_c_dominguez.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
