parameters:
#    my_site_portfolio.example.class: MySite\PortfolioBundle\Example

services:
#    my_site_portfolio.example:
#        class: %my_site_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
