<?php

namespace MySite\DataBaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GastoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoDetalleRepository extends EntityRepository
{
}