<?php

namespace MySite\DataBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoRepository extends EntityRepository
{
    public function loadRecentsByUser($objUser) {
                $q = $this->createQueryBuilder('query')
                        ->select('g')
                        ->from('MySiteDataBaseBundle:Gasto', 'g')
                        ->join('g.usuario', 'u')
                        ->where('u = :user AND g.cuenta is null')
                        ->setParameter('user', $objUser)
                        ->getQuery();

        $gastos = $q->getResult();
        return $gastos;
    }
}