<?php

namespace MySite\DataBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function getDineroGastado($objUser){
        $gastos = $this->getEntityManager()
                            ->getRepository('MySiteDataBaseBundle:Gasto')
                            ->findBy(array('usuario' => $objUser->getId()));
        $total = 0;
        foreach ($gastos as $objGasto) {
            $total += $objGasto->getCantidad();
        }
        return $total;
    }
}