security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MySite\DataBaseBundle\Entity\Usuario:  plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: MySiteDataBaseBundle:Usuario, property: username }

    firewalls:  
        CDominguezApp:
            pattern:    ^/
            anonymous:  ~
            provider:   administrators
            #form_login:
                # the user is redirected here when he/she needs to login
                #login_path:                     /login
                # submit the login form here
                #check_path:                     /login_check
                # by default, the login form *must* be a POST, not a GET
                #post_only:                      true
                # In case no previous URL was stored in the session, you may wish to try using the HTTP_REFERER instead, as this will often be the same. You can do this by setting use_referer to true (it defaults to false):
                #use_referer:                    true
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }