MySiteCDominguezBundle:
    resource: "@MySiteCDominguezBundle/Resources/config/routing.yml"
    prefix:   /

_security_login:
    pattern:  /login
    defaults: { _controller: MySiteCDominguezBundle:Security:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout
    
MySiteOldSiteBundle:
    resource: "@MySiteOldSiteBundle/Resources/config/routing.yml"
    prefix:   /OldSite

MySitePortfolioBundle:
    resource: "@MySitePortfolioBundle/Resources/config/routing.yml"
    prefix:   /Portfolio

BaseFullCalendarBundle:
    resource: "@BaseFullCalendarBundle/Resources/config/routing.yml"
    prefix:   /FullCalendar

BaseUnderConstructionBundle:
    resource: "@BaseUnderConstructionBundle/Resources/config/routing.yml"
    prefix:   /UnderConstruction

BaseJQueryUIBundle:
    resource: "@BaseJQueryUIBundle/Resources/config/routing.yml"
    prefix:   /JQueryUI

BaseEJSTreeGridBundle:
    resource: "@BaseEJSTreeGridBundle/Resources/config/routing.yml"
    prefix:   /EJSTreeGrid

_assetic:
    resource: .
    type:     assetic

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
