security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MySite\DataBaseBundle\Entity\Usuario:  plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: MySiteDataBaseBundle:Usuario, property: username }

    firewalls:  
        CDominguezApp:
            pattern:    ^/
            anonymous:  ~
            provider:   administrators
            form_login:
                # the user is redirected here when he/she needs to login
                login_path:   /cdlogin
            logout:
                path:         /logout
                target:       /cdlogin
                
    access_control:
        - { path: ^/cdlogin, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }