parameters:
#    base_full_calendar.example.class: Base\FullCalendarBundle\Example

services:
#    base_full_calendar.example:
#        class: %base_full_calendar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
