<?php

namespace MySite\DataBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoRepository extends EntityRepository
{
    public function loadRecentsByUserOrderCategoria($objUser) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g, d, c 
             FROM MySiteDataBaseBundle:Gasto g 
                    JOIN g.usuario u 
                    JOIN g.detalle d 
                    JOIN d.categoria c 
             WHERE g.usuario = :puser AND g.cuenta is null 
             ORDER BY c.id, d.id, g.fecha DESC '
        )->setHint("doctrine.includeMetaColumns",true)
        ->setParameter('puser', $objUser);
        $gastos = $query->getResult();
        return $gastos;
    }
    
    public function loadRecentsByUserOrderDia($objUser) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g  
             FROM MySiteDataBaseBundle:Gasto g 
                    JOIN g.usuario u 
                    JOIN g.detalle d 
                    JOIN d.categoria c 
             WHERE g.usuario = :puser AND g.cuenta is null 
             ORDER BY g.fecha DESC '
        )->setHint("doctrine.includeMetaColumns",true)
        ->setParameter('puser', $objUser);
        $gastos = $query->getResult();
        return $gastos;
    }
    
    public function loadByCuentaOrderCategoria($idCuenta) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g, d, c 
             FROM MySiteDataBaseBundle:Gasto g 
                    JOIN g.detalle d 
                    JOIN d.categoria c 
             WHERE g.cuenta = :pidCuenta 
             ORDER BY c.id, d.id, g.fecha DESC '
        )->setParameter('pidCuenta', $idCuenta);
        $gastos = $query->getResult();
        return $gastos;
    }
    
    public function loadByCuentaOrderDia($idCuenta) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT g  
             FROM MySiteDataBaseBundle:Gasto g 
                    JOIN g.detalle d 
                    JOIN d.categoria c 
             WHERE g.cuenta = :pidCuenta 
             ORDER BY g.fecha DESC '
        )->setParameter('pidCuenta', $idCuenta);
        $gastos = $query->getResult();
        return $gastos;
    }
}