<?php

namespace MySite\DataBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GastoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoDetalleRepository extends EntityRepository
{
    public function loadByUserAndCategory($objUser, $objCategory) {
        $q = $this->createQueryBuilder('query')
                ->select('gd')
                ->from('MySiteDataBaseBundle:GastoDetalle', 'gd')
                ->join('gd.categoria', 'c')
                ->join('gd.usuarios', 'u')
                ->where('u = :user AND c = :category')
                ->orderBy('gd.descripcion')
                ->setParameter('user', $objUser)
                ->setParameter('category', $objCategory)
                ->getQuery();

        $gastosDetalles = $q->getResult();
        return $gastosDetalles;
    }
}