parameters:
#    base_highcharts.example.class: Base\HighchartsBundle\Example

services:
#    base_highcharts.example:
#        class: %base_highcharts.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
